apiVersion: v1
kind: Pod
metadata:
  name: bot
spec:
  volumes:
    - name: pv-storage-bot
      persistentVolumeClaim:
        claimName: pvc-bot
  imagePullSecrets:
  - name: regcred
  containers:
  - name: bot
    image: ghcr.io/vryazanov/russian-stock-bot:main
    env:
    {{- range $key, $value := .Values.public_env_variables }}
      - name: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /mnt/storage
        subPath: bot
        name: pv-storage-bot
