secret_env_variables:
    BOT_TOKEN: ENC[AES256_GCM,data:Ew1cr36fiDMkh8/rjcp22WlGVFazyh73Xz4M6/cxIhFRIETIOC7mnsi1kroJdQ==,iv:AYAWhSzl7+zyI8xe92GfkyhrEYDuGoS0x/NXRVNNhjg=,tag:bt9omaaR3xyKFppFIVClnA==,type:str]
    BOT_ADMIN_GROUP: ENC[AES256_GCM,data:w9gy/UsW2gjLCA==,iv:3tSeytAob6G0YP8iyy6XNTdmwlFDm45JZsdDsQWIBzU=,tag:LGqcpUQ2u7zGttlE0NPFSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-20T16:12:00Z"
    mac: ENC[AES256_GCM,data:FvzzqJGYJzh4bmjBGsBOmVQjcZycWH5lVDmDpnB59le68Jn9NNrbwRPVRUshfvE/kKLw0qZMaLW9hnE2qL1a5U1g5bYQHq1ehhdHprgfCeB1kAX35jvfAzR9MjKMVWakpcx7jqo3APXKLNpIQhuER/dtM99YDaCUQARjd8Pbqbo=,iv:AapGDqpSjIl9IYR9WmamE8VCA4YxiqN8u4mkx4LyNYA=,tag:KUjAr+PQhZY7O3UTwPXwrw==,type:str]
    pgp:
        - created_at: "2021-06-20T16:10:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/r/33/eWVcdAQwAmBv2eNF7oja1SG2EkvTPTRHXDfx7QikLcdVfmUtyLWEe
            1CWYgpsVzLv/XF9sXZFesyreNBZACxdNmOauQL+YGZCOe+5r8jvIKRWp4KW8AUO9
            P0pB7UqNGvSFmsN9QJI/0qr7Y6QGs1ctD1Mdy1g9L2KWCjtZI53keh2tcMbuStAA
            UzfhCezHWg0IdMe3AILGUr20/a1qZqUqPLIE0XKEokKur6s5SDBLDEkbBiDbHEk5
            Hb+sJnZcHMWoGQRbnjWuwSD2PzzrUPaFrKKAkSIWEOsEgJ5a5WlIDoS2orBXa6G9
            8Qhd7++Trsl2ap6Ch963VAXE8QhNH9qj07j4mTiTEVkz0/WtkktwD+Pn2/N6xm0C
            +hFNiIsBXre04qvwI9Mvfwb48k04TqD15PpRYaegjII8+vH/nwkKavKrQFNilDs3
            t4AvhA7PIoKJlqPjBrU+Lm8M5bgS+mz/pNlpEzHdREFbtsCpxqv3I1JcDX4UlYqm
            k8QkvYi4RYes7x0p1meI0lwBjy27PJNLS7n2glxTn3mcHiAdGcb4GfzFSb7/uqO9
            zxeCLEA/3V4j+lDCR5sCJ+/GNPCKKHF5Io7vKJZICAyE8qf12NYq63L6qaSgJxEr
            FxlH8cgYWUL36gx04g==
            =32qL
            -----END PGP MESSAGE-----
          fp: DC5BD0445E93FB8BC9B73DB6B7DC290B51D14134
    unencrypted_suffix: _unencrypted
    version: 3.7.1
